language: r
sudo: true
cache: packages
dist: trusty

latex: true

r_github_packages:
  - jimhester/covr

env:
  global:
    - MAKEFLAGS="-j 2"

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libudunits2-dev

      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - mkdir -p ~/.R/
  - echo "CXX14 = g++-7 -fPIC -flto=2" >> ~/.R/Makevars
  - echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars

script:
  - R -q -e "eplusr::install_eplus(8.8)"
  - |
    R CMD build .
    R CMD check epScan*tar.gz

after_script:
  - tar -ztvf epScan_*.tar.gz
  - echo ${NOT_CRAN}

after_success:
  - tar -C .. -xf $PKG_TARBALL
  - Rscript -e 'covr::codecov()'

after_failure:
  - cat epScan.Rcheck/00*
