language: r
sudo: true
cache: packages

latex: true

env:
  global:
    - MAKEFLAGS="-j 2"

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libudunits2-dev
            - libv8-dev
            - libcgal-dev
            - libgdal-dev
            - libglu1-mesa-dev
            - libproj-dev

      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

services:
  - xvfb

before_install:
  - chmod +x configure
  - mkdir -p ~/.R/
  - echo "CXX14 = g++-7 -fPIC -flto=2" >> ~/.R/Makevars
  - echo "CXX14FLAGS = -O3" >> ~/.R/Makevars

script:
  - R -q -e "eplusr::install_eplus(8.8)"
  - |
    travis_wait 20 R CMD build .
    R CMD check epluspar*tar.gz

after_script:
  - tar -ztvf epluspar*.tar.gz

after_success:
  - travis_wait 20 tar -C .. -xf $PKG_TARBALL
  - travis_wait 20 Rscript -e 'covr::codecov()'
  - test $TRAVIS_R_VERSION_STRING = "release" && test $TRAVIS_OS_NAME = "linux" &&
    Rscript -e 'source("https://raw.githubusercontent.com/hongyuanjia/epluspar/master/tools/pkglink.R")' &&
    travis_wait 20 Rscript -e 'pkgdown::build_site(install = TRUE, run_dont_run = TRUE)'

after_failure:
  - cat epluspar.Rcheck/00*

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
    condition: $TRAVIS_R_VERSION_STRING = "release" && $TRAVIS_OS_NAME = "linux"
