// Generated by rstantools.  Do not edit by hand.

/*
    epScan is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    epScan is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with epstan.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.19.1
#include <stan/model/model_header.hpp>
namespace model_bc_with_pred_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_bc_with_pred");
    reader.add_event(101, 99, "end", "model_bc_with_pred");
    return reader;
}
#include <stan_meta_header.hpp>
class model_bc_with_pred : public prob_grad {
private:
        int n;
        int m;
        int n_pred;
        int p;
        int q;
        vector_d yf;
        vector_d yc;
        std::vector<row_vector_d> xf;
        std::vector<row_vector_d> xc;
        std::vector<row_vector_d> tc;
        std::vector<row_vector_d> x_pred;
        double delta;
        int N;
        vector_d y;
        vector_d mu;
        std::vector<row_vector_d> X;
public:
    model_bc_with_pred(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_bc_with_pred(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_bc_with_pred_namespace::model_bc_with_pred";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 2;
            context__.validate_dims("data initialization", "n", "int", context__.to_vec());
            n = int(0);
            vals_i__ = context__.vals_i("n");
            pos__ = 0;
            n = vals_i__[pos__++];
            check_greater_or_equal(function__, "n", n, 1);
            current_statement_begin__ = 3;
            context__.validate_dims("data initialization", "m", "int", context__.to_vec());
            m = int(0);
            vals_i__ = context__.vals_i("m");
            pos__ = 0;
            m = vals_i__[pos__++];
            check_greater_or_equal(function__, "m", m, 1);
            current_statement_begin__ = 4;
            context__.validate_dims("data initialization", "n_pred", "int", context__.to_vec());
            n_pred = int(0);
            vals_i__ = context__.vals_i("n_pred");
            pos__ = 0;
            n_pred = vals_i__[pos__++];
            check_greater_or_equal(function__, "n_pred", n_pred, 1);
            current_statement_begin__ = 5;
            context__.validate_dims("data initialization", "p", "int", context__.to_vec());
            p = int(0);
            vals_i__ = context__.vals_i("p");
            pos__ = 0;
            p = vals_i__[pos__++];
            check_greater_or_equal(function__, "p", p, 1);
            current_statement_begin__ = 6;
            context__.validate_dims("data initialization", "q", "int", context__.to_vec());
            q = int(0);
            vals_i__ = context__.vals_i("q");
            pos__ = 0;
            q = vals_i__[pos__++];
            check_greater_or_equal(function__, "q", q, 1);
            current_statement_begin__ = 7;
            validate_non_negative_index("yf", "n", n);
            context__.validate_dims("data initialization", "yf", "vector_d", context__.to_vec(n));
            yf = Eigen::Matrix<double, Eigen::Dynamic, 1>(n);
            vals_r__ = context__.vals_r("yf");
            pos__ = 0;
            size_t yf_j_1_max__ = n;
            for (size_t j_1__ = 0; j_1__ < yf_j_1_max__; ++j_1__) {
                yf(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 8;
            validate_non_negative_index("yc", "m", m);
            context__.validate_dims("data initialization", "yc", "vector_d", context__.to_vec(m));
            yc = Eigen::Matrix<double, Eigen::Dynamic, 1>(m);
            vals_r__ = context__.vals_r("yc");
            pos__ = 0;
            size_t yc_j_1_max__ = m;
            for (size_t j_1__ = 0; j_1__ < yc_j_1_max__; ++j_1__) {
                yc(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 9;
            validate_non_negative_index("xf", "p", p);
            validate_non_negative_index("xf", "n", n);
            context__.validate_dims("data initialization", "xf", "row_vector_d", context__.to_vec(n,p));
            xf = std::vector<Eigen::Matrix<double, 1, Eigen::Dynamic> >(n, Eigen::Matrix<double, 1, Eigen::Dynamic>(p));
            vals_r__ = context__.vals_r("xf");
            pos__ = 0;
            size_t xf_j_1_max__ = p;
            size_t xf_k_0_max__ = n;
            for (size_t j_1__ = 0; j_1__ < xf_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < xf_k_0_max__; ++k_0__) {
                    xf[k_0__](j_1__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 11;
            validate_non_negative_index("xc", "p", p);
            validate_non_negative_index("xc", "m", m);
            context__.validate_dims("data initialization", "xc", "row_vector_d", context__.to_vec(m,p));
            xc = std::vector<Eigen::Matrix<double, 1, Eigen::Dynamic> >(m, Eigen::Matrix<double, 1, Eigen::Dynamic>(p));
            vals_r__ = context__.vals_r("xc");
            pos__ = 0;
            size_t xc_j_1_max__ = p;
            size_t xc_k_0_max__ = m;
            for (size_t j_1__ = 0; j_1__ < xc_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < xc_k_0_max__; ++k_0__) {
                    xc[k_0__](j_1__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 12;
            validate_non_negative_index("tc", "q", q);
            validate_non_negative_index("tc", "m", m);
            context__.validate_dims("data initialization", "tc", "row_vector_d", context__.to_vec(m,q));
            tc = std::vector<Eigen::Matrix<double, 1, Eigen::Dynamic> >(m, Eigen::Matrix<double, 1, Eigen::Dynamic>(q));
            vals_r__ = context__.vals_r("tc");
            pos__ = 0;
            size_t tc_j_1_max__ = q;
            size_t tc_k_0_max__ = m;
            for (size_t j_1__ = 0; j_1__ < tc_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < tc_k_0_max__; ++k_0__) {
                    tc[k_0__](j_1__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 13;
            validate_non_negative_index("x_pred", "p", p);
            validate_non_negative_index("x_pred", "n_pred", n_pred);
            context__.validate_dims("data initialization", "x_pred", "row_vector_d", context__.to_vec(n_pred,p));
            x_pred = std::vector<Eigen::Matrix<double, 1, Eigen::Dynamic> >(n_pred, Eigen::Matrix<double, 1, Eigen::Dynamic>(p));
            vals_r__ = context__.vals_r("x_pred");
            pos__ = 0;
            size_t x_pred_j_1_max__ = p;
            size_t x_pred_k_0_max__ = n_pred;
            for (size_t j_1__ = 0; j_1__ < x_pred_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < x_pred_k_0_max__; ++k_0__) {
                    x_pred[k_0__](j_1__) = vals_r__[pos__++];
                }
            }
            // initialize transformed data variables
            current_statement_begin__ = 17;
            delta = double(0);
            stan::math::fill(delta, DUMMY_VAR__);
            stan::math::assign(delta,1e-5);
            current_statement_begin__ = 19;
            N = int(0);
            stan::math::fill(N, std::numeric_limits<int>::min());
            current_statement_begin__ = 20;
            validate_non_negative_index("y", "(n + m)", (n + m));
            y = Eigen::Matrix<double, Eigen::Dynamic, 1>((n + m));
            stan::math::fill(y, DUMMY_VAR__);
            current_statement_begin__ = 21;
            validate_non_negative_index("mu", "((n + m) + n_pred)", ((n + m) + n_pred));
            mu = Eigen::Matrix<double, Eigen::Dynamic, 1>(((n + m) + n_pred));
            stan::math::fill(mu, DUMMY_VAR__);
            current_statement_begin__ = 22;
            validate_non_negative_index("X", "p", p);
            validate_non_negative_index("X", "(n + n_pred)", (n + n_pred));
            X = std::vector<Eigen::Matrix<double, 1, Eigen::Dynamic> >((n + n_pred), Eigen::Matrix<double, 1, Eigen::Dynamic>(p));
            stan::math::fill(X, DUMMY_VAR__);
            // execute transformed data statements
            current_statement_begin__ = 24;
            stan::math::assign(N, ((n + m) + n_pred));
            current_statement_begin__ = 26;
            for (int i = 1; i <= N; ++i) {
                current_statement_begin__ = 27;
                stan::model::assign(mu, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            0, 
                            "assigning variable mu");
            }
            current_statement_begin__ = 29;
            stan::model::assign(X, 
                        stan::model::cons_list(stan::model::index_min_max(1, n), stan::model::nil_index_list()), 
                        xf, 
                        "assigning variable X");
            current_statement_begin__ = 30;
            stan::model::assign(X, 
                        stan::model::cons_list(stan::model::index_min_max((n + 1), (n + n_pred)), stan::model::nil_index_list()), 
                        x_pred, 
                        "assigning variable X");
            current_statement_begin__ = 31;
            stan::math::assign(y, append_row(yf, yc));
            // validate transformed data
            current_statement_begin__ = 19;
            check_greater_or_equal(function__, "N", N, 1);
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 40;
            validate_non_negative_index("tf", "q", q);
            num_params_r__ += q;
            current_statement_begin__ = 41;
            validate_non_negative_index("rho_eta", "(p + q)", (p + q));
            num_params_r__ += (p + q);
            current_statement_begin__ = 42;
            num_params_r__ += 1;
            current_statement_begin__ = 43;
            validate_non_negative_index("y_pred", "n_pred", n_pred);
            num_params_r__ += n_pred;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_bc_with_pred() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 40;
        if (!(context__.contains_r("tf")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable tf missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("tf");
        pos__ = 0U;
        validate_non_negative_index("tf", "q", q);
        context__.validate_dims("parameter initialization", "tf", "row_vector_d", context__.to_vec(q));
        Eigen::Matrix<double, 1, Eigen::Dynamic> tf(q);
        size_t tf_j_1_max__ = q;
        for (size_t j_1__ = 0; j_1__ < tf_j_1_max__; ++j_1__) {
            tf(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.row_vector_lub_unconstrain(0, 1, tf);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable tf: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 41;
        if (!(context__.contains_r("rho_eta")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable rho_eta missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("rho_eta");
        pos__ = 0U;
        validate_non_negative_index("rho_eta", "(p + q)", (p + q));
        context__.validate_dims("parameter initialization", "rho_eta", "row_vector_d", context__.to_vec((p + q)));
        Eigen::Matrix<double, 1, Eigen::Dynamic> rho_eta((p + q));
        size_t rho_eta_j_1_max__ = (p + q);
        for (size_t j_1__ = 0; j_1__ < rho_eta_j_1_max__; ++j_1__) {
            rho_eta(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.row_vector_lub_unconstrain(0, 1, rho_eta);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable rho_eta: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 42;
        if (!(context__.contains_r("sigma_e")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable sigma_e missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("sigma_e");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "sigma_e", "double", context__.to_vec());
        double sigma_e(0);
        sigma_e = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, sigma_e);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable sigma_e: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 43;
        if (!(context__.contains_r("y_pred")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable y_pred missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("y_pred");
        pos__ = 0U;
        validate_non_negative_index("y_pred", "n_pred", n_pred);
        context__.validate_dims("parameter initialization", "y_pred", "vector_d", context__.to_vec(n_pred));
        Eigen::Matrix<double, Eigen::Dynamic, 1> y_pred(n_pred);
        size_t y_pred_j_1_max__ = n_pred;
        for (size_t j_1__ = 0; j_1__ < y_pred_j_1_max__; ++j_1__) {
            y_pred(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(y_pred);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable y_pred: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 40;
            Eigen::Matrix<local_scalar_t__, 1, Eigen::Dynamic> tf;
            (void) tf;  // dummy to suppress unused var warning
            if (jacobian__)
                tf = in__.row_vector_lub_constrain(0, 1, q, lp__);
            else
                tf = in__.row_vector_lub_constrain(0, 1, q);
            current_statement_begin__ = 41;
            Eigen::Matrix<local_scalar_t__, 1, Eigen::Dynamic> rho_eta;
            (void) rho_eta;  // dummy to suppress unused var warning
            if (jacobian__)
                rho_eta = in__.row_vector_lub_constrain(0, 1, (p + q), lp__);
            else
                rho_eta = in__.row_vector_lub_constrain(0, 1, (p + q));
            current_statement_begin__ = 42;
            local_scalar_t__ sigma_e;
            (void) sigma_e;  // dummy to suppress unused var warning
            if (jacobian__)
                sigma_e = in__.scalar_lb_constrain(0, lp__);
            else
                sigma_e = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 43;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> y_pred;
            (void) y_pred;  // dummy to suppress unused var warning
            if (jacobian__)
                y_pred = in__.vector_constrain(n_pred, lp__);
            else
                y_pred = in__.vector_constrain(n_pred);
            // transformed parameters
            current_statement_begin__ = 49;
            validate_non_negative_index("beta_eta", "(p + q)", (p + q));
            Eigen::Matrix<local_scalar_t__, 1, Eigen::Dynamic> beta_eta((p + q));
            stan::math::initialize(beta_eta, DUMMY_VAR__);
            stan::math::fill(beta_eta, DUMMY_VAR__);
            current_statement_begin__ = 50;
            validate_non_negative_index("xt", "(p + q)", (p + q));
            validate_non_negative_index("xt", "N", N);
            std::vector<Eigen::Matrix<local_scalar_t__, 1, Eigen::Dynamic> > xt(N, Eigen::Matrix<local_scalar_t__, 1, Eigen::Dynamic>((p + q)));
            stan::math::initialize(xt, DUMMY_VAR__);
            stan::math::fill(xt, DUMMY_VAR__);
            // transformed parameters block statements
            current_statement_begin__ = 51;
            stan::math::assign(beta_eta, multiply(-(4.0), stan::math::log(rho_eta)));
            current_statement_begin__ = 53;
            for (int i = 1; i <= n; ++i) {
                current_statement_begin__ = 54;
                stan::model::assign(xt, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            append_col(get_base1(xf, i, "xf", 1), tf), 
                            "assigning variable xt");
            }
            current_statement_begin__ = 56;
            for (int i = (n + 1); i <= (n + m); ++i) {
                current_statement_begin__ = 57;
                stan::model::assign(xt, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            append_col(get_base1(xc, (i - n), "xc", 1), get_base1(tc, (i - n), "tc", 1)), 
                            "assigning variable xt");
            }
            current_statement_begin__ = 59;
            for (int i = ((n + m) + 1); i <= N; ++i) {
                current_statement_begin__ = 60;
                stan::model::assign(xt, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            append_col(get_base1(x_pred, ((i - n) - m), "x_pred", 1), tf), 
                            "assigning variable xt");
            }
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 49;
            size_t beta_eta_j_1_max__ = (p + q);
            for (size_t j_1__ = 0; j_1__ < beta_eta_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(beta_eta(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: beta_eta" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable beta_eta: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 50;
            size_t xt_k_0_max__ = N;
            size_t xt_j_1_max__ = (p + q);
            for (size_t k_0__ = 0; k_0__ < xt_k_0_max__; ++k_0__) {
                for (size_t j_1__ = 0; j_1__ < xt_j_1_max__; ++j_1__) {
                    if (stan::math::is_uninitialized(xt[k_0__](j_1__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: xt" << "[" << k_0__ << "]" << "(" << j_1__ << ")";
                        stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable xt: ") + msg__.str()), current_statement_begin__, prog_reader__());
                    }
                }
            }
            // model body
            {
            current_statement_begin__ = 66;
            validate_non_negative_index("z", "N", N);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> z(N);
            stan::math::initialize(z, DUMMY_VAR__);
            stan::math::fill(z, DUMMY_VAR__);
            current_statement_begin__ = 67;
            validate_non_negative_index("sigma_eta", "N", N);
            validate_non_negative_index("sigma_eta", "N", N);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> sigma_eta(N, N);
            stan::math::initialize(sigma_eta, DUMMY_VAR__);
            stan::math::fill(sigma_eta, DUMMY_VAR__);
            current_statement_begin__ = 68;
            validate_non_negative_index("sigma_z", "N", N);
            validate_non_negative_index("sigma_z", "N", N);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> sigma_z(N, N);
            stan::math::initialize(sigma_z, DUMMY_VAR__);
            stan::math::fill(sigma_z, DUMMY_VAR__);
            current_statement_begin__ = 69;
            validate_non_negative_index("L", "N", N);
            validate_non_negative_index("L", "N", N);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> L(N, N);
            stan::math::initialize(L, DUMMY_VAR__);
            stan::math::fill(L, DUMMY_VAR__);
            current_statement_begin__ = 70;
            validate_non_negative_index("temp_eta", "(p + q)", (p + q));
            Eigen::Matrix<local_scalar_t__, 1, Eigen::Dynamic> temp_eta((p + q));
            stan::math::initialize(temp_eta, DUMMY_VAR__);
            stan::math::fill(temp_eta, DUMMY_VAR__);
            current_statement_begin__ = 72;
            stan::math::assign(z, append_row(y, y_pred));
            current_statement_begin__ = 75;
            for (int i = 1; i <= (N - 1); ++i) {
                current_statement_begin__ = 76;
                stan::model::assign(sigma_eta, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list())), 
                            (1 + delta), 
                            "assigning variable sigma_eta");
                current_statement_begin__ = 77;
                for (int j = (i + 1); j <= N; ++j) {
                    current_statement_begin__ = 78;
                    stan::model::assign(sigma_eta, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list())), 
                                stan::math::exp(-(dot_self(elt_multiply(subtract(get_base1(xt, i, "xt", 1), get_base1(xt, j, "xt", 1)), beta_eta)))), 
                                "assigning variable sigma_eta");
                    current_statement_begin__ = 79;
                    stan::model::assign(sigma_eta, 
                                stan::model::cons_list(stan::model::index_uni(j), stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list())), 
                                get_base1(sigma_eta, i, j, "sigma_eta", 1), 
                                "assigning variable sigma_eta");
                }
            }
            current_statement_begin__ = 82;
            stan::model::assign(sigma_eta, 
                        stan::model::cons_list(stan::model::index_uni(N), stan::model::cons_list(stan::model::index_uni(N), stan::model::nil_index_list())), 
                        (1 + delta), 
                        "assigning variable sigma_eta");
            current_statement_begin__ = 86;
            stan::math::assign(sigma_z, sigma_eta);
            current_statement_begin__ = 89;
            for (int i = 1; i <= n; ++i) {
                current_statement_begin__ = 90;
                stan::model::assign(sigma_z, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list())), 
                            (get_base1(sigma_z, i, i, "sigma_z", 1) + sigma_e), 
                            "assigning variable sigma_z");
            }
            current_statement_begin__ = 94;
            lp_accum__.add(beta_log<propto__>(rho_eta, 1.0, 0.3));
            current_statement_begin__ = 95;
            lp_accum__.add(normal_log<propto__>(sigma_e, 0, 0.05));
            current_statement_begin__ = 97;
            stan::math::assign(L, cholesky_decompose(sigma_z));
            current_statement_begin__ = 98;
            lp_accum__.add(multi_normal_cholesky_log<propto__>(z, mu, L));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("tf");
        names__.push_back("rho_eta");
        names__.push_back("sigma_e");
        names__.push_back("y_pred");
        names__.push_back("beta_eta");
        names__.push_back("xt");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(q);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((p + q));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n_pred);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((p + q));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dims__.push_back((p + q));
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_bc_with_pred_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        Eigen::Matrix<double, 1, Eigen::Dynamic> tf = in__.row_vector_lub_constrain(0, 1, q);
        size_t tf_j_1_max__ = q;
        for (size_t j_1__ = 0; j_1__ < tf_j_1_max__; ++j_1__) {
            vars__.push_back(tf(j_1__));
        }
        Eigen::Matrix<double, 1, Eigen::Dynamic> rho_eta = in__.row_vector_lub_constrain(0, 1, (p + q));
        size_t rho_eta_j_1_max__ = (p + q);
        for (size_t j_1__ = 0; j_1__ < rho_eta_j_1_max__; ++j_1__) {
            vars__.push_back(rho_eta(j_1__));
        }
        double sigma_e = in__.scalar_lb_constrain(0);
        vars__.push_back(sigma_e);
        Eigen::Matrix<double, Eigen::Dynamic, 1> y_pred = in__.vector_constrain(n_pred);
        size_t y_pred_j_1_max__ = n_pred;
        for (size_t j_1__ = 0; j_1__ < y_pred_j_1_max__; ++j_1__) {
            vars__.push_back(y_pred(j_1__));
        }
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            // declare and define transformed parameters
            current_statement_begin__ = 49;
            validate_non_negative_index("beta_eta", "(p + q)", (p + q));
            Eigen::Matrix<double, 1, Eigen::Dynamic> beta_eta((p + q));
            stan::math::initialize(beta_eta, DUMMY_VAR__);
            stan::math::fill(beta_eta, DUMMY_VAR__);
            current_statement_begin__ = 50;
            validate_non_negative_index("xt", "(p + q)", (p + q));
            validate_non_negative_index("xt", "N", N);
            std::vector<Eigen::Matrix<double, 1, Eigen::Dynamic> > xt(N, Eigen::Matrix<double, 1, Eigen::Dynamic>((p + q)));
            stan::math::initialize(xt, DUMMY_VAR__);
            stan::math::fill(xt, DUMMY_VAR__);
            // do transformed parameters statements
            current_statement_begin__ = 51;
            stan::math::assign(beta_eta, multiply(-(4.0), stan::math::log(rho_eta)));
            current_statement_begin__ = 53;
            for (int i = 1; i <= n; ++i) {
                current_statement_begin__ = 54;
                stan::model::assign(xt, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            append_col(get_base1(xf, i, "xf", 1), tf), 
                            "assigning variable xt");
            }
            current_statement_begin__ = 56;
            for (int i = (n + 1); i <= (n + m); ++i) {
                current_statement_begin__ = 57;
                stan::model::assign(xt, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            append_col(get_base1(xc, (i - n), "xc", 1), get_base1(tc, (i - n), "tc", 1)), 
                            "assigning variable xt");
            }
            current_statement_begin__ = 59;
            for (int i = ((n + m) + 1); i <= N; ++i) {
                current_statement_begin__ = 60;
                stan::model::assign(xt, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            append_col(get_base1(x_pred, ((i - n) - m), "x_pred", 1), tf), 
                            "assigning variable xt");
            }
            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            // write transformed parameters
            if (include_tparams__) {
                size_t beta_eta_j_1_max__ = (p + q);
                for (size_t j_1__ = 0; j_1__ < beta_eta_j_1_max__; ++j_1__) {
                    vars__.push_back(beta_eta(j_1__));
                }
                size_t xt_j_1_max__ = (p + q);
                size_t xt_k_0_max__ = N;
                for (size_t j_1__ = 0; j_1__ < xt_j_1_max__; ++j_1__) {
                    for (size_t k_0__ = 0; k_0__ < xt_k_0_max__; ++k_0__) {
                        vars__.push_back(xt[k_0__](j_1__));
                    }
                }
            }
            if (!include_gqs__) return;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    static std::string model_name() {
        return "model_bc_with_pred";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t tf_j_1_max__ = q;
        for (size_t j_1__ = 0; j_1__ < tf_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "tf" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t rho_eta_j_1_max__ = (p + q);
        for (size_t j_1__ = 0; j_1__ < rho_eta_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "rho_eta" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma_e";
        param_names__.push_back(param_name_stream__.str());
        size_t y_pred_j_1_max__ = n_pred;
        for (size_t j_1__ = 0; j_1__ < y_pred_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "y_pred" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t beta_eta_j_1_max__ = (p + q);
            for (size_t j_1__ = 0; j_1__ < beta_eta_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta_eta" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t xt_j_1_max__ = (p + q);
            size_t xt_k_0_max__ = N;
            for (size_t j_1__ = 0; j_1__ < xt_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < xt_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "xt" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        if (!include_gqs__) return;
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t tf_j_1_max__ = q;
        for (size_t j_1__ = 0; j_1__ < tf_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "tf" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t rho_eta_j_1_max__ = (p + q);
        for (size_t j_1__ = 0; j_1__ < rho_eta_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "rho_eta" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma_e";
        param_names__.push_back(param_name_stream__.str());
        size_t y_pred_j_1_max__ = n_pred;
        for (size_t j_1__ = 0; j_1__ < y_pred_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "y_pred" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t beta_eta_j_1_max__ = (p + q);
            for (size_t j_1__ = 0; j_1__ < beta_eta_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta_eta" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t xt_j_1_max__ = (p + q);
            size_t xt_k_0_max__ = N;
            for (size_t j_1__ = 0; j_1__ < xt_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < xt_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "xt" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        if (!include_gqs__) return;
    }
}; // model
}  // namespace
typedef model_bc_with_pred_namespace::model_bc_with_pred stan_model;
#endif
